global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using Northwind.AB.Sales.Backend.BusinessObjects.Aggregates;
global using Northwind.AB.Sales.Backend.BusinessObjects.Exceptions;
global using Northwind.AB.Sales.Backend.BusinessObjects.Interfaces.CreateOrder;
global using Northwind.IA.Sales.Backend.Presenters;
global using Northwind.IA.Sales.Backend.Presenters.ExceptionHandlers;
global using Northwind.IA.Sales.Backend.Presenters.ExceptionHandlers.Resources;
