//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Membership.Entities.Validators.UserRegistration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserRegistrationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRegistrationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Membership.Entities.Validators.UserRegistration.Resources.UserRegistrat" +
                            "ionMessages", typeof(UserRegistrationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de correo no es válido..
        /// </summary>
        internal static string InvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere al menos un dígito en la contraseña..
        /// </summary>
        internal static string PasswordRequiresDigitErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresDigitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere al menos un caracter minúscula en la contraseña..
        /// </summary>
        internal static string PasswordRequiresLowerErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere al menos un caracter no alfanumeríco en la contraseña..
        /// </summary>
        internal static string PasswordRequiresNonAlphanumericErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere al menos un caracter mayúscula en la contraseña..
        /// </summary>
        internal static string PasswordRequiresUpperErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se requiere al menos 6 caracteres en la constraseña..
        /// </summary>
        internal static string PasswordTooShortErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo es requerido..
        /// </summary>
        internal static string RequiredEmailErrorMessage {
            get {
                return ResourceManager.GetString("RequiredEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido..
        /// </summary>
        internal static string RequiredFirstNameErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFirstNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es requerido..
        /// </summary>
        internal static string RequiredLastNameErrorMessage {
            get {
                return ResourceManager.GetString("RequiredLastNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es requerida..
        /// </summary>
        internal static string RequiredPasswordErrorMessage {
            get {
                return ResourceManager.GetString("RequiredPasswordErrorMessage", resourceCulture);
            }
        }
    }
}
