global using Northwind.IA.Sales.Frontend.Views.Resources;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Northwind.IA.Sales.Frontend.Views.ViewModels.CreateOrder;
global using Northwind.AB.Sales.Frontend.BusinessObjects.Interfaces;
global using Northwind.EB.Sales.Entities.DTOs;
global using Microsoft.AspNetCore.Components.Forms;
global using Northwind.EB.Sales.Entities.Validators.Interfaces.Common;
global using Northwind.EB.Sales.Entities.Validators.ValueObjects;