//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Sales.Backend.UseCases.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrderMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrderMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Sales.Backend.UseCases.Resources.CreateOrderMessages", typeof(CreateOrderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador del cliente proporcionado no existe..
        /// </summary>
        internal static string CustomerIdNotFoundError {
            get {
                return ResourceManager.GetString("CustomerIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente {0} tiene un adeudo pendiente de {1}..
        /// </summary>
        internal static string CustomerWithBalanceErrorTemplate {
            get {
                return ResourceManager.GetString("CustomerWithBalanceErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creación de la orden {0} cancelada..
        /// </summary>
        internal static string OrderCreationCancelledTemplate {
            get {
                return ResourceManager.GetString("OrderCreationCancelledTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto {0} no existe..
        /// </summary>
        internal static string ProductIdNotFoundTemplate {
            get {
                return ResourceManager.GetString("ProductIdNotFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden de compra {0} creada..
        /// </summary>
        internal static string PurchaseOrderCreatedTemplate {
            get {
                return ResourceManager.GetString("PurchaseOrderCreatedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado la orden {0} con {1} productos.
        /// </summary>
        internal static string SendEmailBodyTemplate {
            get {
                return ResourceManager.GetString("SendEmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden especial creada..
        /// </summary>
        internal static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de creación de orden de compra..
        /// </summary>
        internal static string StartingPurchaseOrderCreation {
            get {
                return ResourceManager.GetString("StartingPurchaseOrderCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad {0} de {1} no suficiente para producto {2}.
        /// </summary>
        internal static string UnitsInStockLessThanQuantityErrorTemplate {
            get {
                return ResourceManager.GetString("UnitsInStockLessThanQuantityErrorTemplate", resourceCulture);
            }
        }
    }
}
